[#144] Revert secede
It causes weird issue with Lock serialization.
> 2024-07-18 10:48:12,437 - distributed.protocol.pickle - ERROR - Failed to serialize <Thread(Dask-Default-Threads-448686-0, started daemon 23454385190656)>.
Traceback (most recent call last):
  File "/mnt/home/lmeyer/mmoma_venv/lib/python3.10/site-packages/distributed/worker.py", line 3000, in apply_function_simple
    result = function(*args, **kwargs)
  File "/mnt/home/lmeyer/MultimodalUniverse/scripts/legacysurvey/build_parent_sample.py", line 104, in process_healpix
    secede()
  File "/mnt/home/lmeyer/mmoma_venv/lib/python3.10/site-packages/distributed/worker.py", line 2829, in secede
    tpe_secede()  # have this thread secede from the thread pool
  File "/mnt/home/lmeyer/mmoma_venv/lib/python3.10/site-packages/distributed/threadpoolexecutor.py", line 119, in secede
    thread_state.executor._threads.remove(threading.current_thread())
KeyError: <Thread(Dask-Default-Threads-448686-0, started daemon 23454385190656)>